import './styles.css';
import { ABJAD, ELEMENTS, PLANETS, ZODIAC, analyze, compareCelestial, compareElements, compareProfiles, formatNumber, makeMagicSquare, profile } from './engine.js';
import { femaleNames, maleNames } from './data.js';

const STATE_KEYS = ['section', 'text', 'target', 'nameA', 'motherA', 'nameB', 'motherB', 'role', 'father', 'mother', 'awfaqText', 'rank'];
function readSharedState() {
  try {
    const encoded = new URLSearchParams(location.search).get('state');
    return encoded ? JSON.parse(decodeURIComponent(escape(atob(encoded))) || '{}') : {};
  } catch { return {}; }
}
const stored = JSON.parse(localStorage.getItem('hisab-jomal-state') || '{}');
const state = { section: 'calculator', text: '', target: '', nameA: '', motherA: '', nameB: '', motherB: '', role: 'طالب', father: '', mother: '', awfaqText: '', rank: 4, history: [], suggestionLimit: 12, ...stored, ...readSharedState() };
const app = document.querySelector('#app');
const arabicDate = new Intl.DateTimeFormat('ar-EG', { dateStyle: 'long' }).format(new Date());

function persist() { localStorage.setItem('hisab-jomal-state', JSON.stringify(state)); }
function esc(s = '') { return String(s).replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
function toast(message) { document.querySelector('.toast')?.remove(); const e = document.createElement('div'); e.className = 'toast'; e.textContent = message; document.body.append(e); setTimeout(() => e.remove(), 2200); }
function copy(text) { navigator.clipboard?.writeText(text).then(() => toast('تم النسخ')).catch(() => toast('تعذّر النسخ')); }
function shareLink() {
  const shared = Object.fromEntries(STATE_KEYS.map(key => [key, state[key]]));
  const encoded = btoa(unescape(encodeURIComponent(JSON.stringify(shared))));
  return `${location.href.split('?')[0]}?state=${encodeURIComponent(encoded)}`;
}
function copyShareLink() { copy(shareLink()); }
function exportCard(title, lines, filename) {
  const canvas = document.createElement('canvas'); const width = 1200; const height = Math.max(630, 260 + lines.length * 68);
  canvas.width = width; canvas.height = height; const ctx = canvas.getContext('2d');
  ctx.fillStyle = '#f6f3ea'; ctx.fillRect(0, 0, width, height); ctx.fillStyle = '#123c35'; ctx.fillRect(0, 0, width, 18);
  ctx.direction = 'rtl'; ctx.textAlign = 'right'; ctx.fillStyle = '#123c35'; ctx.font = '700 50px Arial'; ctx.fillText(title, width - 75, 110);
  ctx.fillStyle = '#6a756e'; ctx.font = '28px Arial'; ctx.fillText(`حساب الجمل · إبراهيم بن صلاح · ${arabicDate}`, width - 75, 158);
  ctx.strokeStyle = '#d5ddd7'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(75, 190); ctx.lineTo(width - 75, 190); ctx.stroke();
  ctx.fillStyle = '#17322e'; ctx.font = '34px Arial'; lines.forEach((line, i) => ctx.fillText(line, width - 75, 258 + i * 62));
  canvas.toBlob(blob => { if (!blob) return toast('تعذّر إنشاء الصورة'); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${filename}.png`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); toast('تم تصدير البطاقة كصورة'); }, 'image/png');
}
function setSection(id) { state.section = id; persist(); render(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function num(n) { return formatNumber(n); }
function profileCard(p) { const total = p.count || 1; return `<div class="metric"><span>المجموع</span><b>${num(p.total)}</b></div><div class="metric"><span>الباقي ÷٩</span><b>${p.mod9 ? num(p.mod9) : '—'}</b></div><div class="metric"><span>الطبع</span><b>${p.leaders.length ? p.leaders.join(' / ') : '—'}</b></div><div class="metric"><span>الكوكب</span><b>${p.planetLeaders.length ? p.planetLeaders.join(' / ') : '—'}</b></div><div class="metric"><span>البرج</span><b>${p.zodiac ? `${p.zodiac[0]} · ${p.zodiac[1]}` : '—'}</b></div><div class="element-bars">${Object.entries(p.elements).map(([name, count]) => `<div class="element-row"><span>${name}</span><div class="bar"><i style="width:${count / total * 100}%"></i></div><span>${num(count)}</span></div>`).join('')}</div>`; }
function calculator() {
  const result = analyze(state.text); const target = parseArabicNumber(state.target); const percent = target > 0 ? Math.min(100, result.total / target * 100) : 0;
  return `<div class="grid"><main><section class="card"><h2>الحاسبة</h2><p class="muted">اكتب أي نص عربي، وستظهر النتيجة فورًا وفق حساب الجمل المشرقي.</p><textarea id="text" rows="4" placeholder="اكتب العبارة هنا…">${esc(state.text)}</textarea><div class="chips">${['بسم الله الرحمن الرحيم','محمد','داود','جالوت','لا حول ولا قوة إلا بالله'].map(x => `<button class="chip" data-example="${x}">${x}</button>`).join('')}</div><div class="split" style="margin-top:16px"><div><label class="muted">الرقم المستهدف (اختياري)</label><input id="target" inputmode="numeric" value="${esc(state.target)}" placeholder="مثال: ٧٨٦"></div><div class="actions" style="align-items:end"><button class="btn" data-send="names">إرسال إلى الأسماء</button><button class="btn" data-send="awfaq">إرسال إلى الأوفاق</button></div></div>${target > 0 ? `<div class="result"><div class="metric"><span>التقدم نحو الهدف</span><b>${num(Math.round(percent))}%</b></div><div class="bar"><i style="width:${percent}%"></i></div>${result.total === target ? '<b>تطابق تام مع الرقم المستهدف</b>' : ''}</div>` : ''}<div class="actions"><button class="btn primary" data-copy-result>نسخ النتيجة</button><button class="btn" data-export-calculator>تصدير بطاقة</button><button class="btn" data-copy-link>نسخ الرابط</button><button class="btn" data-clear="calculator">مسح</button></div></section><section class="card"><h3>تفصيل الكلمات</h3>${result.words.length ? result.words.map(w => `<details class="word"><summary><b>${esc(w.word)}</b><span>${num(w.total)}</span></summary><div class="letters">${w.letters.map(l => `<span class="letter">${l.raw}${l.raw !== l.normalized ? ` ← ${l.normalized}` : ''} = ${num(l.value)}</span>`).join('')}</div></details>`).join('') : '<p class="muted">ستظهر الكلمات والحروف المحتسبة هنا.</p>'}</section></main><aside><section class="card"><span class="muted">المجموع الحالي</span><div class="hero-number">${num(result.total)}</div><span class="muted">${num(result.count)} حرفًا محتسبًا</span><span class="tag">حساب الجمل المشرقي</span></section><section class="card"><h3>السجل</h3>${state.history.length ? state.history.map((item,i) => `<div class="metric"><button class="btn history" data-history="${i}">${esc(item.text)}</button><b>${num(item.total)}</b></div>`).join('') : '<p class="muted">آخر خمسة إدخالات تظهر هنا.</p>'}</section></aside></div>`;
}
function names() {
  const a = profile(`${state.nameA} ${state.motherA}`), b = profile(`${state.nameB} ${state.motherB}`); const hasPair = state.nameA && state.nameB; const comparison = hasPair ? compareProfiles(a, b, state.role) : null; const elements = hasPair ? compareElements(a, b) : null; const celestial = hasPair ? compareCelestial(a, b) : null;
  return `<section class="card"><h2>الأسماء</h2><p class="muted">الحساب حرفي ومنهجي، وليس توقعًا أو حكمًا على الأشخاص.</p><div class="split"><div><h3>الشخص الأول</h3><input data-field="nameA" value="${esc(state.nameA)}" placeholder="الاسم"><input data-field="motherA" value="${esc(state.motherA)}" placeholder="اسم الأم (اختياري)" style="margin-top:8px"></div><div><h3>الشخص الثاني</h3><input data-field="nameB" value="${esc(state.nameB)}" placeholder="الاسم"><input data-field="motherB" value="${esc(state.motherB)}" placeholder="اسم الأم (اختياري)" style="margin-top:8px"></div></div><div class="actions"><label class="chip">دور الأول <select data-field="role" style="width:auto;padding:0;border:0;background:transparent"><option ${state.role === 'طالب' ? 'selected' : ''}>طالب</option><option ${state.role === 'مطلوب' ? 'selected' : ''}>مطلوب</option></select></label><button class="btn" data-name-example>داود × جالوت</button><button class="btn" data-export-names>تصدير بطاقة</button><button class="btn" data-copy-link>نسخ الرابط</button><button class="btn" data-clear="names">مسح</button></div></section><div class="split"><section class="card"><h3>بطاقة الشخص الأول</h3>${profileCard(a)}${state.motherA ? '<p class="notice">الحساب مدمج مع اسم الأم.</p>' : ''}</section><section class="card"><h3>بطاقة الشخص الثاني</h3>${profileCard(b)}${state.motherB ? '<p class="notice">الحساب مدمج مع اسم الأم.</p>' : ''}</section></div>${comparison ? `<section class="card"><h3>الغالب والمغلوب</h3><div class="result"><b>${comparison.winner === state.role ? esc(state.nameA) : esc(state.nameB)} غالب</b> — ${comparison.winner === state.role ? esc(state.nameB) : esc(state.nameA)} مغلوب<p class="muted">${comparison.reason}</p><span class="tag">GHALIB-SIRR-1.0</span></div></section><section class="card"><h3>التوافق</h3><div class="reference"><div class="result"><b>${elements.kind}</b><p class="muted">${elements.text}</p><span class="tag">TABIA-MASHRIQI-1.0 · COMPAT-ELEMENTS-1.0</span></div><div class="result"><b>المراسلات الفلكية الحرفية</b><p class="muted">${celestial.planet}<br>${celestial.zodiac}</p><span class="tag">FALAK-STATIC-1.0 · BURJ-MOD12-1.0</span></div></div></section>` : ''}${suggestions()}`;
}
function suggestionScore(candidate, parents) {
  const p = profile(candidate); if (!p.leaders.length || !parents.length) return { score: 0, p, labels: [] };
  const opposing = new Set(['نار/ماء','ماء/نار','هواء/تراب','تراب/هواء']); const friends = new Set(['نار/هواء','هواء/نار','ماء/تراب','تراب/ماء']);
  if (p.leaders.some(x => p.leaders.some(y => x !== y && opposing.has(`${x}/${y}`)))) return null;
  let score = 0; const labels = [];
  for (const parent of parents) {
    if (p.leaders.some(x => parent.leaders.some(y => opposing.has(`${x}/${y}`)))) return null;
    const relation = p.leaders.some(x => parent.leaders.includes(x)) ? 'انسجام' : p.leaders.some(x => parent.leaders.some(y => friends.has(`${x}/${y}`))) ? 'صداقة' : 'امتزاج';
    score += relation === 'انسجام' ? 3 : relation === 'صداقة' ? 2 : 1; labels.push(relation);
  }
  return { score, p, labels };
}
function suggestions() { const father = profile(state.father), mother = profile(state.mother); const parents = [father, mother].filter(p => p.count); const list = names => names.filter(x => x !== state.father && x !== state.mother).map(x => ({ name:x, ...suggestionScore(x, parents) })).filter(Boolean).sort((a,b) => b.score-a.score || a.p.count-b.p.count || a.name.localeCompare(b.name, 'ar')); const males = list(maleNames), females = list(femaleNames);
  return `<section class="card"><h2>اقتراح اسم مولود</h2><p class="notice">اقتراح حسابي تراثي اختياري؛ المعنى الحسن وسنّة التسمية مقدمان، وليس حكمًا شرعيًا.</p><div class="split"><input data-field="father" value="${esc(state.father)}" placeholder="اسم الأب"><input data-field="mother" value="${esc(state.mother)}" placeholder="اسم الأم"></div><div class="actions"><button class="btn" data-parent-example>محمد × فاطمة</button><button class="btn" data-clear="parents">مسح</button></div>${parents.length ? `<div class="split" style="margin-top:16px"><div><h3>ذكور متوافقون <span class="tag">${num(males.length)}</span></h3>${males.slice(0,state.suggestionLimit).map(x => `<div class="metric"><button class="btn copy-name" data-copy-name="${x.name}">${x.name}</button><span>${x.p.leaders.join(' / ')} · ${x.labels.join(' + ')}</span></div>`).join('')}</div><div><h3>إناث متوافقات <span class="tag">${num(females.length)}</span></h3>${females.slice(0,state.suggestionLimit).map(x => `<div class="metric"><button class="btn copy-name" data-copy-name="${x.name}">${x.name}</button><span>${x.p.leaders.join(' / ')} · ${x.labels.join(' + ')}</span></div>`).join('')}</div></div>${(males.length>state.suggestionLimit || females.length>state.suggestionLimit) ? '<div class="actions"><button class="btn" data-more-names>عرض المزيد</button></div>' : ''}` : '<p class="muted">أدخل اسم أحد الوالدين أو كليهما لعرض المقترحات.</p>'}<span class="tag">NAME-SUGGEST-1.0 · TABIA-MASHRIQI-1.0</span></section>`;
}
function awfaq() { const source = state.awfaqText || state.text; const result = analyze(source); const magic = makeMagicSquare(state.rank, result.total); const sums = magic.grid.map(row => row.reduce((s,x)=>s+x,0));
  return `<div class="grid"><main><section class="card"><h2>الأوفاق</h2><p class="muted">مربع عددي منتظم؛ تبقى الصفوف والأعمدة والقطران متساوية.</p><textarea id="awfaqText" rows="3" placeholder="اكتب النص الذي تريد تعميره به…">${esc(state.awfaqText)}</textarea><div class="actions"><label class="chip">الرتبة <select id="rank" style="width:auto;padding:0;border:0;background:transparent">${[3,4,5,7,8].map(n=>`<option value="${n}" ${state.rank===n?'selected':''}>${n}×${n}</option>`).join('')}</select></label><button class="btn" data-use-calculator>استخدم نص الحاسبة</button></div><div class="result"><div class="reference"><div>المجموع S<br><b>${num(result.total)}</b></div><div>ثابت C<br><b>${num(magic.C)}</b></div><div>a / d<br><b>${num(magic.a)} / ${num(magic.d)}</b></div><div>خط M<br><b>${num(magic.M)}</b></div><div>الفرق δ<br><b>${num(magic.delta)}</b></div></div></div><div class="magic" style="grid-template-columns:repeat(${magic.n},1fr)">${magic.grid.flatMap((row,r)=>row.map((value,c)=>`<span class="${r===c || r+c===magic.n-1?'diag':''}">${num(value)}</span>`)).join('')}</div><div class="notice">التحقق: مجموع كل صف ${num(sums[0] || 0)} — وفق تام دائمًا. <span class="tag">AWFAQ-SESIANO-2.0</span></div></section></main><aside><section class="card"><h3>عنوان الوفق</h3><p>وفق ${magic.n}×${magic.n} · ثابت الخط M = <b>${num(magic.M)}</b></p><div class="actions"><button class="btn primary" data-copy-magic>نسخ الشبكة</button><button class="btn" data-export-awfaq>تصدير صورة</button><button class="btn" data-copy-link>نسخ الرابط</button></div></section></aside></div>`; }
function reference() { return `<section class="card"><h2>المرجع والمنهج</h2><p class="muted">كل النتائج حسابية بمنهج معلن. لا يستخدم التطبيق أبجدًا مغربيًا أو طالعًا فلكيًا أو مضاعفة للشدة.</p><div class="reference"><div class="card"><h3>الأبجد المشرقي</h3>${Object.entries(ABJAD).map(([l,v])=>`<span class="letter">${l} = ${num(v)}</span>`).join(' ')}</div><div class="card"><h3>الطبائع</h3>${Object.entries(ELEMENTS).map(([e,l])=>`<p><b>${e}</b>: ${l.join(' ')}</p>`).join('')}</div><div class="card"><h3>الكواكب</h3>${PLANETS.map((p,i)=>`<p>${i+1}. ${p}</p>`).join('')}</div><div class="card"><h3>البروج</h3>${ZODIAC.map(([z,e],i)=>`<p>${num(i+1)}. ${z} · ${e}</p>`).join('')}</div></div><div class="actions"><button class="btn primary" data-run-tests>تشغيل الاختبارات الذاتية</button><button class="btn" data-reset-storage>مسح البيانات المحفوظة</button></div><span class="tag">GHALIB-SIRR-1.0 · TABIA-MASHRIQI-1.0 · FALAK-STATIC-1.0 · BURJ-MOD12-1.0</span></section>`; }
function render() { const sectionViews = { calculator, names, awfaq, reference }; const result = analyze(state.text); app.innerHTML = `<div class="shell"><header class="top"><div class="brand"><h1>حساب الجمل</h1><small>إبراهيم بن صلاح · أداة حساب تراثية موثقة</small></div><button class="sum-chip" data-go-calculator><span>المجموع الحالي</span>${num(result.total)}</button></header><nav class="nav">${[['calculator','الحاسبة'],['names','الأسماء'],['awfaq','الأوفاق'],['reference','المرجع']].map(([id,label])=>`<button class="${state.section===id?'active':''}" data-nav="${id}">${label}</button>`).join('')}</nav>${sectionViews[state.section]()}</div>`; attach(); }
function parseArabicNumber(raw) { return Number(String(raw).replace(/[٠-٩]/g, d => '٠١٢٣٤٥٦٧٨٩'.indexOf(d)).replace(/[^0-9]/g,'')) || 0; }
function commitText(value) { state.text = value; persist(); }
function recordHistory() { const value = state.text.trim(); const result = analyze(value); if (value && result.total) state.history = [{ text:value, total:result.total }, ...state.history.filter(x => x.text !== value)].slice(0, 5); }
let redrawTimer;
function redrawKeepingFocus(selector, cursor) {
  clearTimeout(redrawTimer);
  redrawTimer = setTimeout(() => {
    if (selector === '#text') recordHistory();
    render();
    const field = document.querySelector(selector);
    if (field) { field.focus(); field.setSelectionRange?.(cursor, cursor); }
  }, 260);
}
function attach() { document.querySelectorAll('[data-nav]').forEach(e=>e.onclick=()=>setSection(e.dataset.nav)); document.querySelector('[data-go-calculator]')?.addEventListener('click',()=>setSection('calculator'));
  document.querySelector('#text')?.addEventListener('input', e=>{ const cursor=e.target.selectionStart; commitText(e.target.value); redrawKeepingFocus('#text', cursor); }); document.querySelector('#target')?.addEventListener('input', e=>{const cursor=e.target.selectionStart;state.target=e.target.value;persist();redrawKeepingFocus('#target',cursor);}); document.querySelectorAll('[data-example]').forEach(e=>e.onclick=()=>{commitText(e.dataset.example);render();}); document.querySelectorAll('[data-history]').forEach(e=>e.onclick=()=>{state.text=state.history[e.dataset.history].text;persist();render();});
  document.querySelectorAll('[data-field]').forEach(e=>{const update=()=>{const cursor=e.target.selectionStart;const selector=`[data-field="${e.dataset.field}"]`;state[e.dataset.field]=e.target.value;persist();redrawKeepingFocus(selector,cursor);};e.addEventListener('input',update);e.addEventListener('change',update);}); document.querySelector('#awfaqText')?.addEventListener('input',e=>{const cursor=e.target.selectionStart;state.awfaqText=e.target.value;persist();redrawKeepingFocus('#awfaqText',cursor);}); document.querySelector('#rank')?.addEventListener('change',e=>{state.rank=Number(e.target.value);persist();render();});
  document.querySelectorAll('[data-send]').forEach(e=>e.onclick=()=>{ if(e.dataset.send==='names') state.nameA=state.text; else state.awfaqText=state.text; setSection(e.dataset.send); }); document.querySelector('[data-name-example]')?.addEventListener('click',()=>{state.nameA='داود';state.nameB='جالوت';persist();render();}); document.querySelector('[data-parent-example]')?.addEventListener('click',()=>{state.father='محمد';state.mother='فاطمة';state.suggestionLimit=12;persist();render();}); document.querySelector('[data-use-calculator]')?.addEventListener('click',()=>{state.awfaqText=state.text;persist();render();}); document.querySelector('[data-more-names]')?.addEventListener('click',()=>{state.suggestionLimit+=12;persist();render();});
  document.querySelector('[data-copy-result]')?.addEventListener('click',()=>{const r=analyze(state.text);copy(`${state.text}\nالمجموع: ${num(r.total)}\nعدد الحروف: ${num(r.count)}`)}); document.querySelector('[data-copy-magic]')?.addEventListener('click',()=>{const m=makeMagicSquare(state.rank,analyze(state.awfaqText||state.text).total);copy(m.grid.map(row=>row.map(num).join(' | ')).join('\n'));}); document.querySelectorAll('[data-copy-name]').forEach(e=>e.onclick=()=>copy(e.dataset.copyName)); document.querySelectorAll('[data-copy-link]').forEach(e=>e.onclick=copyShareLink);
  document.querySelector('[data-export-calculator]')?.addEventListener('click',()=>{const r=analyze(state.text);if(!r.total)return toast('اكتب نصًا أولًا');exportCard('بطاقة حساب الجمل',[state.text,`المجموع: ${num(r.total)}`,`الحروف المحتسبة: ${num(r.count)}`,`عيّنة الحروف: ${r.letters.slice(0,24).map(x=>x.normalized).join(' ')}`],'hisab-jomal');}); document.querySelector('[data-export-names]')?.addEventListener('click',()=>{const a=profile(`${state.nameA} ${state.motherA}`),b=profile(`${state.nameB} ${state.motherB}`);if(!a.total&&!b.total)return toast('أدخل اسمًا أولًا');exportCard('بطاقة الأسماء',[`${state.nameA || '—'}: ${num(a.total)} · ${a.leaders.join(' / ') || '—'}`,`${state.nameB || '—'}: ${num(b.total)} · ${b.leaders.join(' / ') || '—'}`],'hisab-names');}); document.querySelector('[data-export-awfaq]')?.addEventListener('click',()=>{const r=analyze(state.awfaqText||state.text);if(!r.total)return toast('اكتب نصًا أولًا');const m=makeMagicSquare(state.rank,r.total);exportCard(`وفق ${m.n}×${m.n}`,[`المجموع S: ${num(r.total)}`,`ثابت الخط M: ${num(m.M)}`,`a = ${num(m.a)} · d = ${num(m.d)}`,...m.grid.map(row=>row.map(num).join('  |  '))],'wafq');});
  document.querySelectorAll('[data-clear]').forEach(e=>e.onclick=()=>{if(e.dataset.clear==='calculator'){state.text='';state.target='';}if(e.dataset.clear==='names'){state.nameA='';state.nameB='';state.motherA='';state.motherB='';}if(e.dataset.clear==='parents'){state.father='';state.mother='';state.suggestionLimit=12;}persist();render();toast('تم المسح');}); document.querySelector('[data-run-tests]')?.addEventListener('click',()=>{const tests=[['بسم الله الرحمن الرحيم',786],['داود',15],['جالوت',440],['محمد',92],['فاطمة',135],['أإآء',4]];const passed=tests.every(([x,n])=>analyze(x).total===n);toast(passed?'نجحت جميع الاختبارات المرجعية':'فشل اختبار ذاتي');}); document.querySelector('[data-reset-storage]')?.addEventListener('click',()=>{localStorage.removeItem('hisab-jomal-state');location.reload();}); }
render();
