import './styles.css';
import { ABJAD, ELEMENTS, PLANETS, ZODIAC, analyze, compareCelestial, compareElements, compareProfiles, formatNumber, profile } from './engine.js';
import { femaleNames, maleNames } from './data.js';
import { ELEMENT_GUIDE, QUALITY_GUIDE, ZODIAC_DETAILS, ZODIAC_SOURCES, zodiacFromDate, zodiacFromNumber } from './zodiac.js';

const STATE_KEYS = ['section', 'text', 'target', 'nameA', 'motherA', 'nameB', 'motherB', 'role', 'father', 'mother', 'desiredBabyName', 'maleSearch', 'femaleSearch', 'zodiacName', 'zodiacMother', 'birthDate'];
function readSharedState() {
  try {
    const encoded = new URLSearchParams(location.search).get('state');
    return encoded ? JSON.parse(decodeURIComponent(escape(atob(encoded))) || '{}') : {};
  } catch { return {}; }
}
const stored = JSON.parse(localStorage.getItem('hisab-jomal-state') || '{}');
const state = { section: 'names', text: '', target: '', nameA: '', motherA: '', nameB: '', motherB: '', role: 'طالب', father: '', mother: '', desiredBabyName: '', maleSearch: '', femaleSearch: '', zodiacName: '', zodiacMother: '', birthDate: '', history: [], suggestionLimit: 12, ...stored, ...readSharedState() };
if (!['names', 'calculator', 'zodiac', 'reference'].includes(state.section)) state.section = 'names';
const app = document.querySelector('#app');
const arabicDate = new Intl.DateTimeFormat('ar-EG', { dateStyle: 'long' }).format(new Date());

function persist() { localStorage.setItem('hisab-jomal-state', JSON.stringify(state)); }
function esc(s = '') { return String(s).replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
function toast(message) { document.querySelector('.toast')?.remove(); const e = document.createElement('div'); e.className = 'toast'; e.textContent = message; document.body.append(e); setTimeout(() => e.remove(), 2200); }
function copy(text) { navigator.clipboard?.writeText(text).then(() => toast('تم النسخ')).catch(() => toast('تعذّر النسخ')); }
function shareLink() {
  const shared = Object.fromEntries(STATE_KEYS.map(key => [key, state[key]]));
  const encoded = btoa(unescape(encodeURIComponent(JSON.stringify(shared))));
  return `${location.href.split('?')[0]}?state=${encodeURIComponent(encoded)}`;
}
function copyShareLink() { copy(shareLink()); }
function copyNameComparison() {
  const a = profile(`${state.nameA} ${state.motherA}`), b = profile(`${state.nameB} ${state.motherB}`);
  if (!state.nameA.trim() || !state.nameB.trim() || !a.mod9 || !b.mod9) return toast('أدخل الاسمين أولًا');
  const firstRole = state.role, secondRole = firstRole === 'طالب' ? 'مطلوب' : 'طالب';
  const comparison = compareProfiles(a, b, firstRole), elements = compareElements(a, b), celestial = compareCelestial(a, b);
  const firstWins = comparison.winner === firstRole;
  const winner = firstWins ? state.nameA : state.nameB, loser = firstWins ? state.nameB : state.nameA;
  copy([`مقارنة الأسماء`,`${state.nameA} (${firstRole}): المجموع ${num(a.total)} · الباقي ${num(a.mod9)} · الطبع ${a.leaders.join(' / ') || '—'}`,`${state.nameB} (${secondRole}): المجموع ${num(b.total)} · الباقي ${num(b.mod9)} · الطبع ${b.leaders.join(' / ') || '—'}`,`${winner} غالب — ${loser} مغلوب`,comparison.reason,`${elements.kind}: ${elements.text}`,celestial.planet,celestial.zodiac].join('\n'));
}
function exportCard(title, lines, filename) {
  const canvas = document.createElement('canvas'); const width = 1200; const height = Math.max(630, 260 + lines.length * 68);
  canvas.width = width; canvas.height = height; const ctx = canvas.getContext('2d');
  ctx.fillStyle = '#f6f3ea'; ctx.fillRect(0, 0, width, height); ctx.fillStyle = '#123c35'; ctx.fillRect(0, 0, width, 18);
  ctx.direction = 'rtl'; ctx.textAlign = 'right'; ctx.fillStyle = '#123c35'; ctx.font = '700 50px Arial'; ctx.fillText(title, width - 75, 110);
  ctx.fillStyle = '#6a756e'; ctx.font = '28px Arial'; ctx.fillText(`أطلس الحروف · إبراهيم بن صلاح · ${arabicDate}`, width - 75, 158);
  ctx.strokeStyle = '#d5ddd7'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(75, 190); ctx.lineTo(width - 75, 190); ctx.stroke();
  ctx.fillStyle = '#17322e'; ctx.font = '34px Arial'; lines.forEach((line, i) => ctx.fillText(line, width - 75, 258 + i * 62));
  canvas.toBlob(blob => { if (!blob) return toast('تعذّر إنشاء الصورة'); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${filename}.png`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); toast('تم تصدير البطاقة كصورة'); }, 'image/png');
}
function setSection(id) { state.section = id; persist(); render(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function num(n) { return formatNumber(n); }
function profileCard(p) { const total = p.count || 1; return `<div class="metric"><span>المجموع</span><b>${num(p.total)}</b></div><div class="metric"><span>الباقي ÷٩</span><b>${p.mod9 ? num(p.mod9) : '—'}</b></div><div class="metric"><span>الطبع</span><b>${p.leaders.length ? p.leaders.join(' / ') : '—'}</b></div><div class="metric"><span>الكوكب</span><b>${p.planetLeaders.length ? p.planetLeaders.join(' / ') : '—'}</b></div><div class="metric"><span>البرج</span><b>${p.zodiac ? `${p.zodiac[0]} · ${p.zodiac[1]}` : '—'}</b></div><div class="element-bars">${Object.entries(p.elements).map(([name, count]) => `<div class="element-row"><span>${name}</span><div class="bar"><i style="width:${count / total * 100}%"></i></div><span>${num(count)}</span></div>`).join('')}</div>`; }
function calculator() {
  const result = analyze(state.text); const target = parseArabicNumber(state.target); const percent = target > 0 ? Math.min(100, result.total / target * 100) : 0;
  return `<div class="grid"><main><section class="card"><h2>الحاسبة</h2><p class="muted">اكتب أي نص عربي، وستظهر النتيجة فورًا وفق حساب الجمل المشرقي.</p><textarea id="text" rows="4" placeholder="اكتب العبارة هنا…">${esc(state.text)}</textarea><div class="chips">${['بسم الله الرحمن الرحيم','محمد','داود','جالوت','لا حول ولا قوة إلا بالله'].map(x => `<button class="chip" data-example="${x}">${x}</button>`).join('')}</div><div class="split" style="margin-top:16px"><div><label class="muted">الرقم المستهدف (اختياري)</label><input id="target" inputmode="numeric" value="${esc(state.target)}" placeholder="مثال: ٧٨٦"></div><div class="actions" style="align-items:end"><button class="btn" data-send="names">إرسال إلى الأسماء</button></div></div>${target > 0 ? `<div class="result"><div class="metric"><span>التقدم نحو الهدف</span><b>${num(Math.round(percent))}%</b></div><div class="bar"><i style="width:${percent}%"></i></div>${result.total === target ? '<b>تطابق تام مع الرقم المستهدف</b>' : ''}</div>` : ''}<div class="actions"><button class="btn primary" data-copy-result>نسخ النتيجة</button><button class="btn" data-export-calculator>تصدير بطاقة</button><button class="btn" data-copy-link>نسخ الرابط</button><button class="btn" data-clear="calculator">مسح</button></div></section><section class="card"><h3>تفصيل الكلمات</h3>${result.words.length ? result.words.map(w => `<details class="word"><summary><b>${esc(w.word)}</b><span>${num(w.total)}</span></summary><div class="letters">${w.letters.map(l => `<span class="letter">${l.raw}${l.raw !== l.normalized ? ` ← ${l.normalized}` : ''} = ${num(l.value)}</span>`).join('')}</div></details>`).join('') : '<p class="muted">ستظهر الكلمات والحروف المحتسبة هنا.</p>'}</section></main><aside><section class="card"><span class="muted">المجموع الحالي</span><div class="hero-number">${num(result.total)}</div><span class="muted">${num(result.count)} حرفًا محتسبًا</span><span class="tag">حساب الجمل المشرقي</span></section><section class="card"><h3>السجل</h3>${state.history.length ? state.history.map((item,i) => `<div class="metric"><button class="btn history" data-history="${i}">${esc(item.text)}</button><b>${num(item.total)}</b></div>`).join('') : '<p class="muted">آخر خمسة إدخالات تظهر هنا.</p>'}</section></aside></div>`;
}
function comparePersonCard(label, role, name, motherName, p, isWinner) {
  return `<article class="compare-person ${p.count ? '' : 'is-empty'} ${isWinner ? 'is-winner' : ''}"><div class="compare-person-top"><span>${label} · ${role}</span>${isWinner ? '<b class="winner-chip">الغالب</b>' : ''}</div><h3>${esc(name.trim() || 'الاسم غير مُدخل')}</h3>${motherName ? `<small>مع اسم الأم: ${esc(motherName)}</small>` : ''}${p.count ? `<div class="compare-total"><strong>${num(p.total)}</strong><span>المجموع</span></div><div class="person-stats"><span>الباقي ÷٩ <b>${num(p.mod9)}</b></span><span>الطبع <b>${p.leaders.join(' / ') || '—'}</b></span><span>البرج <b>${p.zodiac ? p.zodiac[0] : '—'}</b></span></div>` : '<p>أدخل الاسم لعرض بياناته.</p>'}</article>`;
}
function nameComparison(a, b) {
  const firstRole = state.role;
  const secondRole = firstRole === 'طالب' ? 'مطلوب' : 'طالب';
  const ready = Boolean(state.nameA.trim() && state.nameB.trim() && a.mod9 && b.mod9);
  const comparison = ready ? compareProfiles(a, b, firstRole) : null;
  const elements = ready ? compareElements(a, b) : null;
  const celestial = ready ? compareCelestial(a, b) : null;
  const firstWins = Boolean(comparison && comparison.winner === firstRole);
  const winnerName = firstWins ? state.nameA : state.nameB;
  const loserName = firstWins ? state.nameB : state.nameA;
  const result = ready ? `<div class="dominance-verdict" id="comparison-result"><span class="verdict-label">نتيجة الغالب والمغلوب</span><div class="verdict-line"><strong>${esc(winnerName)}</strong><b>غالب</b><i></i><span>${esc(loserName)}</span><small>مغلوب</small></div><p>${comparison.reason}</p></div><div class="comparison-insights"><article><span class="insight-number">١</span><div><small>قاعدة الحكم</small><h3>الباقي من القسمة على ٩</h3><p>${comparison.reason}</p></div></article><article><span class="insight-number">٢</span><div><small>علاقة الطبائع</small><h3>${elements.kind}</h3><p>${elements.text}</p></div></article><article><span class="insight-number">٣</span><div><small>المراسلات الحرفية</small><h3>${celestial.planet}</h3><p>${celestial.zodiac}</p></div></article></div><details class="comparison-details"><summary>عرض التفاصيل الحسابية الكاملة للشخصين</summary><div class="split"><div class="profile-detail"><h3>${esc(state.nameA)}</h3>${profileCard(a)}</div><div class="profile-detail"><h3>${esc(state.nameB)}</h3>${profileCard(b)}</div></div></details><div class="method-tags"><span class="tag">GHALIB-SIRR-1.0</span><span class="tag">COMPAT-ELEMENTS-1.0</span><span class="tag">FALAK-STATIC-1.0</span></div>` : '<div class="comparison-placeholder"><b>أدخل الاسمين لإظهار المقارنة الموحّدة</b><span>ستظهر النتيجة والطبائع والمراسلات في لوحة واحدة.</span></div>';
  return `<section class="card comparison-workspace" id="name-comparison"><div class="section-heading"><div><h2>مقارنة الأسماء</h2><p class="muted">لوحة واحدة تجمع الحساب والغالب والمغلوب والتوافق.</p></div><span class="tag">NAME-COMPARE-2.0</span></div><div class="comparison-inputs"><label><span>الشخص الأول</span><input data-field="nameA" value="${esc(state.nameA)}" placeholder="الاسم"><input data-field="motherA" value="${esc(state.motherA)}" placeholder="اسم الأم (اختياري)"></label><label><span>الشخص الثاني</span><input data-field="nameB" value="${esc(state.nameB)}" placeholder="الاسم"><input data-field="motherB" value="${esc(state.motherB)}" placeholder="اسم الأم (اختياري)"></label></div><div class="actions comparison-actions"><label class="chip">دور الشخص الأول <select data-field="role" style="width:auto;padding:0;border:0;background:transparent"><option ${firstRole === 'طالب' ? 'selected' : ''}>طالب</option><option ${firstRole === 'مطلوب' ? 'selected' : ''}>مطلوب</option></select></label><button class="btn" data-name-example>تجربة داود × جالوت</button><button class="btn primary" data-copy-comparison>نسخ المقارنة</button><button class="btn" data-export-names>تصدير بطاقة</button><button class="btn" data-copy-link>نسخ الرابط</button><button class="btn" data-clear="names">مسح</button></div><div class="duel-grid">${comparePersonCard('الشخص الأول', firstRole, state.nameA, state.motherA, a, ready && firstWins)}<div class="versus-mark"><b>↔</b><span>مقارنة</span></div>${comparePersonCard('الشخص الثاني', secondRole, state.nameB, state.motherB, b, ready && !firstWins)}</div>${result}</section>`;
}
function names() {
  const a = profile(`${state.nameA} ${state.motherA}`), b = profile(`${state.nameB} ${state.motherB}`);
  return `${suggestions()}${nameComparison(a, b)}`;
}
function assessBabyName(candidate, parentEntries) {
  const p = profile(candidate);
  const opposing = new Set(['نار/ماء','ماء/نار','هواء/تراب','تراب/هواء']); const friends = new Set(['نار/هواء','هواء/نار','ماء/تراب','تراب/ماء']);
  if (!p.leaders.length) return { compatible: false, score: 0, p, relations: [], reason: 'الاسم لا يحتوي على حروف عربية محسوبة.' };
  if (p.leaders.some(x => p.leaders.some(y => x !== y && opposing.has(`${x}/${y}`)))) return { compatible: false, score: 0, p, relations: [], reason: 'طبائع الاسم نفسه متضادة حسابيًا.' };
  let score = 0; const relations = [];
  for (const entry of parentEntries) {
    const parent = entry.profile;
    if (p.leaders.some(x => parent.leaders.some(y => opposing.has(`${x}/${y}`)))) return { compatible: false, score: 0, p, relations, reason: `يوجد تضاد حسابي مع ${entry.label}.` };
    const relation = p.leaders.some(x => parent.leaders.includes(x)) ? 'انسجام' : p.leaders.some(x => parent.leaders.some(y => friends.has(`${x}/${y}`))) ? 'صداقة' : 'امتزاج';
    score += relation === 'انسجام' ? 3 : relation === 'صداقة' ? 2 : 1; relations.push({ label: entry.label, relation });
  }
  return { compatible: true, score, p, relations, reason: 'لا يوجد تضاد حسابي مع بيانات الوالدين المدخلة.' };
}
function babyVerdict(match, parentCount) {
  if (!match?.compatible) return 'غير متوافق حسابيًا';
  const ratio = match.score / Math.max(1, parentCount * 3);
  return ratio >= 1 ? 'متوافق جدًا' : ratio >= .67 ? 'متوافق' : 'متوافق بدرجة مقبولة';
}
function suggestedNameList(items, emptyText) {
  if (!items.length) return `<p class="muted empty-state">${emptyText}</p>`;
  return `<div class="name-options">${items.slice(0, state.suggestionLimit).map(x => `<button class="name-option" data-select-name="${esc(x.name)}"><span><strong>${esc(x.name)}</strong><small>${x.p.leaders.join(' / ')} · ${x.relations.map(r => r.relation).join(' + ')}</small></span><em>${babyVerdict(x, x.relations.length)}</em></button>`).join('')}</div>`;
}
function suggestions() {
  const father = profile(state.father), mother = profile(state.mother);
  const parentEntries = [{ label: 'الأب', name: state.father, profile: father }, { label: 'الأم', name: state.mother, profile: mother }].filter(entry => entry.profile.count);
  const desired = profile(state.desiredBabyName);
  const desiredMatch = desired.count && parentEntries.length ? assessBabyName(state.desiredBabyName, parentEntries) : null;
  const list = (names, query) => names
    .filter(name => name !== state.father && name !== state.mother)
    .filter(name => !query.trim() || name.includes(query.trim()))
    .map(name => ({ name, ...assessBabyName(name, parentEntries) }))
    .filter(item => item.compatible)
    .sort((a,b) => b.score-a.score || a.p.count-b.p.count || a.name.localeCompare(b.name, 'ar'));
  const males = parentEntries.length ? list(maleNames, state.maleSearch) : [];
  const females = parentEntries.length ? list(femaleNames, state.femaleSearch) : [];
  const desiredResult = !desired.count
    ? '<div class="baby-empty"><b>اكتب الاسم المرغوب</b><span>سنحسب قيمته ونقارنه بالأب والأم فورًا.</span></div>'
    : !parentEntries.length
      ? `<div class="baby-result neutral"><div><span class="muted">حساب الاسم</span><strong>${num(desired.total)}</strong></div><p>أدخل اسم الأب أو الأم لإظهار درجة التوافق.</p></div>`
      : `<div class="baby-result ${desiredMatch.compatible ? 'compatible' : 'incompatible'}"><div class="baby-result-head"><div><span class="muted">نتيجة ${esc(state.desiredBabyName)}</span><strong>${num(desired.total)}</strong></div><span class="status-badge">${babyVerdict(desiredMatch, parentEntries.length)}</span></div><div class="baby-facts"><span>الطبع <b>${desired.leaders.join(' / ') || '—'}</b></span><span>الكوكب <b>${desired.planetLeaders.join(' / ') || '—'}</b></span><span>البرج <b>${desired.zodiac ? desired.zodiac[0] : '—'}</b></span></div>${desiredMatch.relations.length ? `<div class="relation-chips">${desiredMatch.relations.map(item => `<span>${item.label}: <b>${item.relation}</b></span>`).join('')}</div>` : ''}<p>${desiredMatch.reason}</p></div>`;
  return `<section class="card baby-planner"><div class="section-heading"><div><h2>اقتراح اسم مولود</h2><p class="muted">أدخل بيانات الوالدين ثم جرّب اسمًا مرغوبًا أو اختر من المقترحات.</p></div><span class="tag">NAME-SUGGEST-2.0</span></div><p class="notice">اقتراح حسابي تراثي اختياري؛ المعنى الحسن وسنّة التسمية مقدمان، وليس حكمًا شرعيًا.</p><div class="baby-inputs"><label><span>اسم الأب</span><input data-field="father" value="${esc(state.father)}" placeholder="مثال: محمد"></label><label><span>اسم الأم</span><input data-field="mother" value="${esc(state.mother)}" placeholder="مثال: فاطمة"></label><label class="desired-name"><span>الاسم المرغوب للمولود</span><input data-field="desiredBabyName" value="${esc(state.desiredBabyName)}" placeholder="اكتب الاسم الذي تفكران فيه"></label></div>${desiredResult}<div class="actions"><button class="btn" data-parent-example>تجربة محمد × فاطمة</button><button class="btn" data-clear="parents">مسح بيانات المولود</button></div></section>${parentEntries.length ? `<div class="suggestion-columns"><section class="card suggestion-panel"><div class="suggestion-title"><div><span class="gender-mark male">ذ</span><div><h3>أسماء ذكور مقترحة</h3><span class="muted">${num(males.length)} اسمًا متوافقًا</span></div></div></div><input data-field="maleSearch" value="${esc(state.maleSearch)}" placeholder="ابحث في أسماء الذكور…">${suggestedNameList(males, 'لا توجد أسماء ذكور مطابقة للبحث.')}</section><section class="card suggestion-panel"><div class="suggestion-title"><div><span class="gender-mark female">أ</span><div><h3>أسماء إناث مقترحة</h3><span class="muted">${num(females.length)} اسمًا متوافقًا</span></div></div></div><input data-field="femaleSearch" value="${esc(state.femaleSearch)}" placeholder="ابحث في أسماء الإناث…">${suggestedNameList(females, 'لا توجد أسماء إناث مطابقة للبحث.')}</section></div>${(males.length>state.suggestionLimit || females.length>state.suggestionLimit) ? '<div class="actions centered"><button class="btn" data-more-names>عرض أسماء أكثر</button></div>' : ''}` : '<section class="card baby-prompt"><b>ابدأ باسم الأب أو الأم</b><span>بعدها ستظهر هنا قوائم منفصلة للأسماء الذكور والإناث.</span></section>'}`;
}
function heritageZodiacResult() {
  const person = analyze(state.zodiacName);
  const mother = analyze(state.zodiacMother);
  const total = person.total + mother.total;
  const remainder = total ? total % 12 || 12 : null;
  return { person, mother, total, remainder, sign: zodiacFromNumber(remainder) };
}
function traitList(items) { return `<ul>${items.map(item => `<li>${item}</li>`).join('')}</ul>`; }
function zodiacGuideCard(sign, index) {
  return `<article class="zodiac-card"><div class="zodiac-card-top"><span>${sign.symbol}</span><small>${num(index + 1)}</small></div><h3>${sign.name}</h3><p class="zodiac-dates">${sign.dates}</p><div class="zodiac-tags"><span>${sign.element}</span><span>${sign.quality}</span><span>${sign.ruler}</span></div><p>${sign.summary}</p></article>`;
}
function zodiac() {
  const heritage = heritageZodiacResult();
  const solar = zodiacFromDate(state.birthDate);
  const sources = ZODIAC_SOURCES.map(([institution, title, url], index) => `<a class="source-link" href="${url}" target="_blank" rel="noreferrer"><span>${num(index + 1)}</span><div><strong>${institution}</strong><small>${title}</small></div><b aria-hidden="true">↗</b></a>`).join('');
  const result = heritage.sign ? `<section class="zodiac-result"><div class="zodiac-emblem"><span>${heritage.sign.symbol}</span><small>الباقي ${num(heritage.remainder)} من ١٢</small></div><div class="zodiac-reading"><span class="eyebrow">البرج الحرفي التراثي</span><h2>${heritage.sign.name}</h2><p>${heritage.sign.summary}</p><div class="zodiac-facts"><span>العنصر<b>${heritage.sign.element}</b></span><span>الكيفية<b>${heritage.sign.quality}</b></span><span>الكوكب المنسوب تراثيًا<b>${heritage.sign.ruler}</b></span></div><div class="calculation-strip"><span>${esc(state.zodiacName)} <b>${num(heritage.person.total)}</b></span><i>+</i><span>${state.zodiacMother.trim() ? esc(state.zodiacMother) : 'اسم الأم غير مُدخل'} <b>${state.zodiacMother.trim() ? num(heritage.mother.total) : '—'}</b></span><i>=</i><span>المجموع <b>${num(heritage.total)}</b></span></div>${!state.zodiacMother.trim() ? '<p class="partial-note">هذه نتيجة جزئية من الاسم وحده؛ النص التراثي الموثّق يذكر جمع الاسم مع اسم الأم.</p>' : ''}<div class="trait-columns"><div><h3>رموز إيجابية محتملة</h3>${traitList(heritage.sign.strengths)}</div><div><h3>مساحات للتوازن</h3>${traitList(heritage.sign.balance)}</div></div><p class="reading-note">هذه قراءة رمزية حديثة مبنية على عنصر البرج وكيفيته، وليست تشخيصًا علميًا للشخصية.</p><div class="actions"><button class="btn primary" data-copy-zodiac>نسخ النتيجة</button><button class="btn" data-copy-link>نسخ الرابط</button><button class="btn" data-clear="zodiac">مسح</button></div></div></section>` : '<section class="zodiac-empty"><span>١٢</span><div><b>اكتب الاسم لتظهر القراءة الحرفية</b><p>ويُفضّل إضافة اسم الأم لتطبيق الطريقة كما وردت في المصدر التراثي.</p></div></section>';
  const solarResult = solar ? `<article class="solar-result"><span class="solar-symbol">${solar.symbol}</span><div><small>برج تاريخ الميلاد المتداول</small><h3>${solar.name}</h3><p>${solar.dates}</p></div><p>${heritage.sign ? (heritage.sign.name === solar.name ? 'اتفقت الطريقتان في الاسم فقط؛ لا يمنح ذلك دلالة إضافية.' : 'الاختلاف طبيعي: الحساب الحرفي وتاريخ الميلاد طريقتان مختلفتان.') : 'هذا تصنيف شمسي متداول بحسب تاريخ الميلاد، وليس طالعًا فلكيًا.'}</p></article>` : '<article class="solar-placeholder"><b>المقارنة بالتاريخ اختيارية</b><span>أدخل تاريخ الميلاد لعرض البرج الشمسي المتداول بجانب الحساب الحرفي.</span></article>';
  return `<section class="zodiac-hero"><div><span class="eyebrow">معرفة تراثية بحدود واضحة</span><h2>الأبراج بين الحروف والتاريخ</h2><p>حاسبة موثّقة لطريقة الاسم واسم الأم، ودليل بصري للأبراج الاثني عشر دون تنبؤات أو ادعاءات غيبية.</p></div><div class="zodiac-orbit"><span>١٢</span>${ZODIAC_DETAILS.map((_, index) => `<i style="--i:${index}"></i>`).join('')}</div></section>
  <section class="card zodiac-calculator"><div class="section-heading"><div><h2>احسب البرج الحرفي</h2><p class="muted">نجمع قيمة الاسم واسم الأم بالأبجد المشرقي، ثم نأخذ الباقي من القسمة على ١٢.</p></div><span class="tag">BURJ-NAME-MOD12-1.0</span></div><div class="zodiac-inputs"><label><span>اسم الشخص</span><input data-field="zodiacName" value="${esc(state.zodiacName)}" placeholder="مثال: محمد"></label><label><span>اسم الأم</span><input data-field="zodiacMother" value="${esc(state.zodiacMother)}" placeholder="مثال: فاطمة"></label><label><span>تاريخ الميلاد (اختياري)</span><input type="date" data-field="birthDate" value="${esc(state.birthDate)}"></label></div><div class="actions"><button class="btn" data-zodiac-example>تجربة محمد بن فاطمة</button></div>${result}${solarResult}</section>
  <section class="card zodiac-method"><div class="section-heading"><div><span class="eyebrow">كيف تم الحساب؟</span><h2>طريقة قابلة للمراجعة خطوة بخطوة</h2></div><span class="tag">HERITAGE · NOT SCIENCE</span></div><div class="method-steps"><article><span>١</span><h3>تحويل الحروف</h3><p>تُحوّل حروف الاسم واسم الأم إلى قيم الأبجد المشرقي.</p></article><article><span>٢</span><h3>جمع القيم</h3><p>يُجمع الاسمان كما يذكر المخطوط المنشور في مكتبة قطر الرقمية.</p></article><article><span>٣</span><h3>الباقي من ١٢</h3><p>١ للحمل، ثم بالترتيب حتى ١٢ للحوت؛ وهو ما تؤكده الدراسة الأكاديمية.</p></article></div><div class="element-quality-grid">${Object.entries(ELEMENT_GUIDE).map(([element, guide]) => `<article><b>${element}</b><span>${guide.label}</span><p>${guide.text}</p></article>`).join('')}${Object.entries(QUALITY_GUIDE).map(([quality, text]) => `<article><b>${quality}</b><span>كيفية تراثية</span><p>${text}</p></article>`).join('')}</div></section>
  <section class="zodiac-boundaries"><article><span>✓</span><div><small>موثّق تاريخيًا</small><h3>طريقة الأسماء والباقي ١–١٢</h3><p>وجودها في مخطوط ودراسة أكاديمية يثبت تاريخ الفكرة وطريقة حسابها.</p></div></article><article><span>≈</span><div><small>غير مثبت علميًا</small><h3>ليست اختبار شخصية</h3><p>علم النفس لا يعد الأبراج وسيلة مثبتة لقياس الشخصية؛ وقد فشلت اختبارات مضبوطة في إثبات قدرتها الوصفية.</p></div></article><article><span>!</span><div><small>تنبيه ديني</small><h3>لا تنبؤ ولا ادعاء غيب</h3><p>لا يقدم التطبيق حظًا أو مستقبلًا أو أحكامًا مصيرية، اتساقًا مع تحذير دار الإفتاء المصرية من الاعتقاد بالطالع.</p></div></article></section>
  <section class="card"><div class="section-heading"><div><span class="eyebrow">الدليل الكامل</span><h2>الأبراج الاثنا عشر</h2><p class="muted">العناصر والكيفيات والكواكب هنا مراسلات تاريخية؛ والعبارات الشخصية قراءة رمزية مختصرة.</p></div></div><div class="zodiac-guide">${ZODIAC_DETAILS.map(zodiacGuideCard).join('')}</div></section>
  <section class="card sources-section"><div class="section-heading"><div><span class="eyebrow">المراجع</span><h2>مصادر أصلية وأكاديمية وعلمية</h2><p class="muted">تفتح الروابط المادة الأصلية حتى تستطيع مراجعة المنهج وحدوده بنفسك.</p></div><span class="tag">SOURCES-2.0</span></div><div class="source-list">${sources}</div></section>`;
}
function reference() { return `<section class="card"><h2>المرجع والمنهج</h2><p class="muted">كل النتائج حسابية بمنهج معلن. يستخدم التطبيق الأبجد المشرقي ولا يضاعف الشدة. ويعرض قسم الأبراج الحساب الحرفي التراثي منفصلًا عن برج تاريخ الميلاد.</p><div class="reference"><div class="card"><h3>الأبجد المشرقي</h3>${Object.entries(ABJAD).map(([l,v])=>`<span class="letter">${l} = ${num(v)}</span>`).join(' ')}</div><div class="card"><h3>الطبائع</h3>${Object.entries(ELEMENTS).map(([e,l])=>`<p><b>${e}</b>: ${l.join(' ')}</p>`).join('')}</div><div class="card"><h3>الكواكب</h3>${PLANETS.map((p,i)=>`<p>${i+1}. ${p}</p>`).join('')}</div><div class="card"><h3>البروج</h3>${ZODIAC.map(([z,e],i)=>`<p>${num(i+1)}. ${z} · ${e}</p>`).join('')}</div></div><div class="actions"><button class="btn primary" data-run-tests>تشغيل الاختبارات الذاتية</button><button class="btn" data-reset-storage>مسح البيانات المحفوظة</button></div><span class="tag">GHALIB-SIRR-1.0 · TABIA-MASHRIQI-1.0 · FALAK-STATIC-1.0 · BURJ-NAME-MOD12-1.0</span></section>`; }
function render() { const sectionViews = { names, calculator, zodiac, reference }; const result = analyze(state.text); const view = sectionViews[state.section] || names; app.innerHTML = `<div class="shell"><header class="top"><div class="brand"><img src="./assets/atlas-al-huruf-icon.png" alt=""><div><h1>أطلس الحروف</h1><small>الأسماء وحساب الحروف · قراءة تراثية موثّقة</small></div></div><button class="sum-chip" data-go-calculator><span>المجموع الحالي</span>${num(result.total)}</button></header><nav class="nav">${[['names','الأسماء'],['calculator','الحاسبة'],['zodiac','الأبراج'],['reference','المرجع']].map(([id,label])=>`<button class="${state.section===id?'active':''}" data-nav="${id}">${label}</button>`).join('')}</nav>${view()}</div>`; attach(); }
function parseArabicNumber(raw) { return Number(String(raw).replace(/[٠-٩]/g, d => '٠١٢٣٤٥٦٧٨٩'.indexOf(d)).replace(/[^0-9]/g,'')) || 0; }
function commitText(value) { state.text = value; persist(); }
function recordHistory() { const value = state.text.trim(); const result = analyze(value); if (value && result.total) state.history = [{ text:value, total:result.total }, ...state.history.filter(x => x.text !== value)].slice(0, 5); }
let redrawTimer;
function redrawKeepingFocus(selector, cursor) {
  clearTimeout(redrawTimer);
  redrawTimer = setTimeout(() => {
    if (selector === '#text') recordHistory();
    render();
    const field = document.querySelector(selector);
    if (field) { field.focus(); if (cursor !== null) { try { field.setSelectionRange?.(cursor, cursor); } catch {} } }
  }, 260);
}
function attach() { document.querySelectorAll('[data-nav]').forEach(e=>e.onclick=()=>setSection(e.dataset.nav)); document.querySelector('[data-go-calculator]')?.addEventListener('click',()=>setSection('calculator'));
  document.querySelector('#text')?.addEventListener('input', e=>{ const cursor=e.target.selectionStart; commitText(e.target.value); redrawKeepingFocus('#text', cursor); }); document.querySelector('#target')?.addEventListener('input', e=>{const cursor=e.target.selectionStart;state.target=e.target.value;persist();redrawKeepingFocus('#target',cursor);}); document.querySelectorAll('[data-example]').forEach(e=>e.onclick=()=>{commitText(e.dataset.example);render();}); document.querySelectorAll('[data-history]').forEach(e=>e.onclick=()=>{state.text=state.history[e.dataset.history].text;persist();render();});
  document.querySelectorAll('[data-field]').forEach(field=>{const update=event=>{const input=event.currentTarget;const cursor=typeof input.selectionStart==='number'?input.selectionStart:null;const selector=`[data-field="${input.dataset.field}"]`;state[input.dataset.field]=input.value;persist();if(input.tagName==='SELECT'||input.type==='date')render();else redrawKeepingFocus(selector,cursor);};field.addEventListener('input',update);field.addEventListener('change',update);});
  document.querySelectorAll('[data-send]').forEach(e=>e.onclick=()=>{state.nameA=state.text;setSection('names');}); document.querySelector('[data-name-example]')?.addEventListener('click',()=>{state.nameA='داود';state.nameB='جالوت';persist();render();}); document.querySelector('[data-parent-example]')?.addEventListener('click',()=>{state.father='محمد';state.mother='فاطمة';state.desiredBabyName='';state.maleSearch='';state.femaleSearch='';state.suggestionLimit=12;persist();render();}); document.querySelector('[data-zodiac-example]')?.addEventListener('click',()=>{state.zodiacName='محمد';state.zodiacMother='فاطمة';state.birthDate='';persist();render();}); document.querySelectorAll('[data-select-name]').forEach(e=>e.addEventListener('click',()=>{state.desiredBabyName=e.dataset.selectName;persist();render();document.querySelector('[data-field="desiredBabyName"]')?.scrollIntoView({behavior:'smooth',block:'center'});})); document.querySelector('[data-more-names]')?.addEventListener('click',()=>{state.suggestionLimit+=12;persist();render();});
  document.querySelector('[data-copy-result]')?.addEventListener('click',()=>{const r=analyze(state.text);copy(`${state.text}\nالمجموع: ${num(r.total)}\nعدد الحروف: ${num(r.count)}`)}); document.querySelector('[data-copy-comparison]')?.addEventListener('click',copyNameComparison); document.querySelector('[data-copy-zodiac]')?.addEventListener('click',()=>{const r=heritageZodiacResult();if(!r.sign)return toast('اكتب الاسم أولًا');copy([`أطلس الحروف — البرج الحرفي التراثي`,`الاسم: ${state.zodiacName} (${num(r.person.total)})`,`اسم الأم: ${state.zodiacMother || 'غير مُدخل'}${state.zodiacMother ? ` (${num(r.mother.total)})` : ''}`,`المجموع: ${num(r.total)} · الباقي من ١٢: ${num(r.remainder)}`,`النتيجة: ${r.sign.name} · ${r.sign.element} · ${r.sign.quality} · ${r.sign.ruler}`,'قراءة رمزية تراثية؛ ليست وصفًا علميًا للشخصية أو تنبؤًا.'].join('\n'));}); document.querySelectorAll('[data-copy-name]').forEach(e=>e.onclick=()=>copy(e.dataset.copyName)); document.querySelectorAll('[data-copy-link]').forEach(e=>e.onclick=copyShareLink);
  document.querySelector('[data-export-calculator]')?.addEventListener('click',()=>{const r=analyze(state.text);if(!r.total)return toast('اكتب نصًا أولًا');exportCard('بطاقة حساب الجمل',[state.text,`المجموع: ${num(r.total)}`,`الحروف المحتسبة: ${num(r.count)}`,`عيّنة الحروف: ${r.letters.slice(0,24).map(x=>x.normalized).join(' ')}`],'atlas-al-huruf');}); document.querySelector('[data-export-names]')?.addEventListener('click',()=>{const a=profile(`${state.nameA} ${state.motherA}`),b=profile(`${state.nameB} ${state.motherB}`);if(!a.total&&!b.total)return toast('أدخل اسمًا أولًا');exportCard('بطاقة الأسماء',[`${state.nameA || '—'}: ${num(a.total)} · ${a.leaders.join(' / ') || '—'}`,`${state.nameB || '—'}: ${num(b.total)} · ${b.leaders.join(' / ') || '—'}`],'atlas-al-huruf-names');});
  document.querySelectorAll('[data-clear]').forEach(e=>e.onclick=()=>{if(e.dataset.clear==='calculator'){state.text='';state.target='';}if(e.dataset.clear==='names'){state.nameA='';state.nameB='';state.motherA='';state.motherB='';}if(e.dataset.clear==='parents'){state.father='';state.mother='';state.desiredBabyName='';state.maleSearch='';state.femaleSearch='';state.suggestionLimit=12;}if(e.dataset.clear==='zodiac'){state.zodiacName='';state.zodiacMother='';state.birthDate='';}persist();render();toast('تم المسح');}); document.querySelector('[data-run-tests]')?.addEventListener('click',()=>{const tests=[['بسم الله الرحمن الرحيم',786],['داود',15],['جالوت',440],['محمد',92],['فاطمة',135],['أإآء',4]];const passed=tests.every(([x,n])=>analyze(x).total===n)&&zodiacFromNumber((92+135)%12).name==='الدلو'&&zodiacFromDate('1990-04-01').name==='الحمل';toast(passed?'نجحت جميع الاختبارات المرجعية':'فشل اختبار ذاتي');}); document.querySelector('[data-reset-storage]')?.addEventListener('click',()=>{localStorage.removeItem('hisab-jomal-state');location.reload();}); }
render();
