import './styles.css';
import { ABJAD, ELEMENTS, PLANETS, ZODIAC, analyze, compareCelestial, compareElements, compareProfiles, formatNumber, makeMagicSquare, profile } from './engine.js';
import { femaleNames, maleNames } from './data.js';

const STATE_KEYS = ['section', 'text', 'target', 'nameA', 'motherA', 'nameB', 'motherB', 'role', 'father', 'mother', 'desiredBabyName', 'maleSearch', 'femaleSearch', 'awfaqText', 'rank', 'awfaqMode'];
function readSharedState() {
  try {
    const encoded = new URLSearchParams(location.search).get('state');
    return encoded ? JSON.parse(decodeURIComponent(escape(atob(encoded))) || '{}') : {};
  } catch { return {}; }
}
const stored = JSON.parse(localStorage.getItem('hisab-jomal-state') || '{}');
const state = { section: 'calculator', text: '', target: '', nameA: '', motherA: '', nameB: '', motherB: '', role: 'طالب', father: '', mother: '', desiredBabyName: '', maleSearch: '', femaleSearch: '', awfaqText: '', rank: 4, awfaqMode: 'square', history: [], suggestionLimit: 12, ...stored, ...readSharedState() };
const app = document.querySelector('#app');
const arabicDate = new Intl.DateTimeFormat('ar-EG', { dateStyle: 'long' }).format(new Date());

function persist() { localStorage.setItem('hisab-jomal-state', JSON.stringify(state)); }
function esc(s = '') { return String(s).replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
function toast(message) { document.querySelector('.toast')?.remove(); const e = document.createElement('div'); e.className = 'toast'; e.textContent = message; document.body.append(e); setTimeout(() => e.remove(), 2200); }
function copy(text) { navigator.clipboard?.writeText(text).then(() => toast('تم النسخ')).catch(() => toast('تعذّر النسخ')); }
function shareLink() {
  const shared = Object.fromEntries(STATE_KEYS.map(key => [key, state[key]]));
  const encoded = btoa(unescape(encodeURIComponent(JSON.stringify(shared))));
  return `${location.href.split('?')[0]}?state=${encodeURIComponent(encoded)}`;
}
function copyShareLink() { copy(shareLink()); }
function copyNameComparison() {
  const a = profile(`${state.nameA} ${state.motherA}`), b = profile(`${state.nameB} ${state.motherB}`);
  if (!state.nameA.trim() || !state.nameB.trim() || !a.mod9 || !b.mod9) return toast('أدخل الاسمين أولًا');
  const firstRole = state.role, secondRole = firstRole === 'طالب' ? 'مطلوب' : 'طالب';
  const comparison = compareProfiles(a, b, firstRole), elements = compareElements(a, b), celestial = compareCelestial(a, b);
  const firstWins = comparison.winner === firstRole;
  const winner = firstWins ? state.nameA : state.nameB, loser = firstWins ? state.nameB : state.nameA;
  copy([`مقارنة الأسماء`,`${state.nameA} (${firstRole}): المجموع ${num(a.total)} · الباقي ${num(a.mod9)} · الطبع ${a.leaders.join(' / ') || '—'}`,`${state.nameB} (${secondRole}): المجموع ${num(b.total)} · الباقي ${num(b.mod9)} · الطبع ${b.leaders.join(' / ') || '—'}`,`${winner} غالب — ${loser} مغلوب`,comparison.reason,`${elements.kind}: ${elements.text}`,celestial.planet,celestial.zodiac].join('\n'));
}
function exportCard(title, lines, filename) {
  const canvas = document.createElement('canvas'); const width = 1200; const height = Math.max(630, 260 + lines.length * 68);
  canvas.width = width; canvas.height = height; const ctx = canvas.getContext('2d');
  ctx.fillStyle = '#f6f3ea'; ctx.fillRect(0, 0, width, height); ctx.fillStyle = '#123c35'; ctx.fillRect(0, 0, width, 18);
  ctx.direction = 'rtl'; ctx.textAlign = 'right'; ctx.fillStyle = '#123c35'; ctx.font = '700 50px Arial'; ctx.fillText(title, width - 75, 110);
  ctx.fillStyle = '#6a756e'; ctx.font = '28px Arial'; ctx.fillText(`حساب الجمل · إبراهيم بن صلاح · ${arabicDate}`, width - 75, 158);
  ctx.strokeStyle = '#d5ddd7'; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(75, 190); ctx.lineTo(width - 75, 190); ctx.stroke();
  ctx.fillStyle = '#17322e'; ctx.font = '34px Arial'; lines.forEach((line, i) => ctx.fillText(line, width - 75, 258 + i * 62));
  canvas.toBlob(blob => { if (!blob) return toast('تعذّر إنشاء الصورة'); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${filename}.png`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); toast('تم تصدير البطاقة كصورة'); }, 'image/png');
}
function setSection(id) { state.section = id; persist(); render(); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function num(n) { return formatNumber(n); }
function profileCard(p) { const total = p.count || 1; return `<div class="metric"><span>المجموع</span><b>${num(p.total)}</b></div><div class="metric"><span>الباقي ÷٩</span><b>${p.mod9 ? num(p.mod9) : '—'}</b></div><div class="metric"><span>الطبع</span><b>${p.leaders.length ? p.leaders.join(' / ') : '—'}</b></div><div class="metric"><span>الكوكب</span><b>${p.planetLeaders.length ? p.planetLeaders.join(' / ') : '—'}</b></div><div class="metric"><span>البرج</span><b>${p.zodiac ? `${p.zodiac[0]} · ${p.zodiac[1]}` : '—'}</b></div><div class="element-bars">${Object.entries(p.elements).map(([name, count]) => `<div class="element-row"><span>${name}</span><div class="bar"><i style="width:${count / total * 100}%"></i></div><span>${num(count)}</span></div>`).join('')}</div>`; }
function calculator() {
  const result = analyze(state.text); const target = parseArabicNumber(state.target); const percent = target > 0 ? Math.min(100, result.total / target * 100) : 0;
  return `<div class="grid"><main><section class="card"><h2>الحاسبة</h2><p class="muted">اكتب أي نص عربي، وستظهر النتيجة فورًا وفق حساب الجمل المشرقي.</p><textarea id="text" rows="4" placeholder="اكتب العبارة هنا…">${esc(state.text)}</textarea><div class="chips">${['بسم الله الرحمن الرحيم','محمد','داود','جالوت','لا حول ولا قوة إلا بالله'].map(x => `<button class="chip" data-example="${x}">${x}</button>`).join('')}</div><div class="split" style="margin-top:16px"><div><label class="muted">الرقم المستهدف (اختياري)</label><input id="target" inputmode="numeric" value="${esc(state.target)}" placeholder="مثال: ٧٨٦"></div><div class="actions" style="align-items:end"><button class="btn" data-send="names">إرسال إلى الأسماء</button><button class="btn" data-send="awfaq">إرسال إلى الأوفاق</button></div></div>${target > 0 ? `<div class="result"><div class="metric"><span>التقدم نحو الهدف</span><b>${num(Math.round(percent))}%</b></div><div class="bar"><i style="width:${percent}%"></i></div>${result.total === target ? '<b>تطابق تام مع الرقم المستهدف</b>' : ''}</div>` : ''}<div class="actions"><button class="btn primary" data-copy-result>نسخ النتيجة</button><button class="btn" data-export-calculator>تصدير بطاقة</button><button class="btn" data-copy-link>نسخ الرابط</button><button class="btn" data-clear="calculator">مسح</button></div></section><section class="card"><h3>تفصيل الكلمات</h3>${result.words.length ? result.words.map(w => `<details class="word"><summary><b>${esc(w.word)}</b><span>${num(w.total)}</span></summary><div class="letters">${w.letters.map(l => `<span class="letter">${l.raw}${l.raw !== l.normalized ? ` ← ${l.normalized}` : ''} = ${num(l.value)}</span>`).join('')}</div></details>`).join('') : '<p class="muted">ستظهر الكلمات والحروف المحتسبة هنا.</p>'}</section></main><aside><section class="card"><span class="muted">المجموع الحالي</span><div class="hero-number">${num(result.total)}</div><span class="muted">${num(result.count)} حرفًا محتسبًا</span><span class="tag">حساب الجمل المشرقي</span></section><section class="card"><h3>السجل</h3>${state.history.length ? state.history.map((item,i) => `<div class="metric"><button class="btn history" data-history="${i}">${esc(item.text)}</button><b>${num(item.total)}</b></div>`).join('') : '<p class="muted">آخر خمسة إدخالات تظهر هنا.</p>'}</section></aside></div>`;
}
function comparePersonCard(label, role, name, motherName, p, isWinner) {
  return `<article class="compare-person ${p.count ? '' : 'is-empty'} ${isWinner ? 'is-winner' : ''}"><div class="compare-person-top"><span>${label} · ${role}</span>${isWinner ? '<b class="winner-chip">الغالب</b>' : ''}</div><h3>${esc(name.trim() || 'الاسم غير مُدخل')}</h3>${motherName ? `<small>مع اسم الأم: ${esc(motherName)}</small>` : ''}${p.count ? `<div class="compare-total"><strong>${num(p.total)}</strong><span>المجموع</span></div><div class="person-stats"><span>الباقي ÷٩ <b>${num(p.mod9)}</b></span><span>الطبع <b>${p.leaders.join(' / ') || '—'}</b></span><span>البرج <b>${p.zodiac ? p.zodiac[0] : '—'}</b></span></div>` : '<p>أدخل الاسم لعرض بياناته.</p>'}</article>`;
}
function nameComparison(a, b) {
  const firstRole = state.role;
  const secondRole = firstRole === 'طالب' ? 'مطلوب' : 'طالب';
  const ready = Boolean(state.nameA.trim() && state.nameB.trim() && a.mod9 && b.mod9);
  const comparison = ready ? compareProfiles(a, b, firstRole) : null;
  const elements = ready ? compareElements(a, b) : null;
  const celestial = ready ? compareCelestial(a, b) : null;
  const firstWins = Boolean(comparison && comparison.winner === firstRole);
  const winnerName = firstWins ? state.nameA : state.nameB;
  const loserName = firstWins ? state.nameB : state.nameA;
  const result = ready ? `<div class="dominance-verdict" id="comparison-result"><span class="verdict-label">نتيجة الغالب والمغلوب</span><div class="verdict-line"><strong>${esc(winnerName)}</strong><b>غالب</b><i></i><span>${esc(loserName)}</span><small>مغلوب</small></div><p>${comparison.reason}</p></div><div class="comparison-insights"><article><span class="insight-number">١</span><div><small>قاعدة الحكم</small><h3>الباقي من القسمة على ٩</h3><p>${comparison.reason}</p></div></article><article><span class="insight-number">٢</span><div><small>علاقة الطبائع</small><h3>${elements.kind}</h3><p>${elements.text}</p></div></article><article><span class="insight-number">٣</span><div><small>المراسلات الحرفية</small><h3>${celestial.planet}</h3><p>${celestial.zodiac}</p></div></article></div><details class="comparison-details"><summary>عرض التفاصيل الحسابية الكاملة للشخصين</summary><div class="split"><div class="profile-detail"><h3>${esc(state.nameA)}</h3>${profileCard(a)}</div><div class="profile-detail"><h3>${esc(state.nameB)}</h3>${profileCard(b)}</div></div></details><div class="method-tags"><span class="tag">GHALIB-SIRR-1.0</span><span class="tag">COMPAT-ELEMENTS-1.0</span><span class="tag">FALAK-STATIC-1.0</span></div>` : '<div class="comparison-placeholder"><b>أدخل الاسمين لإظهار المقارنة الموحّدة</b><span>ستظهر النتيجة والطبائع والمراسلات في لوحة واحدة.</span></div>';
  return `<section class="card comparison-workspace" id="name-comparison"><div class="section-heading"><div><h2>مقارنة الأسماء</h2><p class="muted">لوحة واحدة تجمع الحساب والغالب والمغلوب والتوافق.</p></div><span class="tag">NAME-COMPARE-2.0</span></div><div class="comparison-inputs"><label><span>الشخص الأول</span><input data-field="nameA" value="${esc(state.nameA)}" placeholder="الاسم"><input data-field="motherA" value="${esc(state.motherA)}" placeholder="اسم الأم (اختياري)"></label><label><span>الشخص الثاني</span><input data-field="nameB" value="${esc(state.nameB)}" placeholder="الاسم"><input data-field="motherB" value="${esc(state.motherB)}" placeholder="اسم الأم (اختياري)"></label></div><div class="actions comparison-actions"><label class="chip">دور الشخص الأول <select data-field="role" style="width:auto;padding:0;border:0;background:transparent"><option ${firstRole === 'طالب' ? 'selected' : ''}>طالب</option><option ${firstRole === 'مطلوب' ? 'selected' : ''}>مطلوب</option></select></label><button class="btn" data-name-example>تجربة داود × جالوت</button><button class="btn primary" data-copy-comparison>نسخ المقارنة</button><button class="btn" data-export-names>تصدير بطاقة</button><button class="btn" data-copy-link>نسخ الرابط</button><button class="btn" data-clear="names">مسح</button></div><div class="duel-grid">${comparePersonCard('الشخص الأول', firstRole, state.nameA, state.motherA, a, ready && firstWins)}<div class="versus-mark"><b>↔</b><span>مقارنة</span></div>${comparePersonCard('الشخص الثاني', secondRole, state.nameB, state.motherB, b, ready && !firstWins)}</div>${result}</section>`;
}
function names() {
  const a = profile(`${state.nameA} ${state.motherA}`), b = profile(`${state.nameB} ${state.motherB}`);
  return `${suggestions()}${nameComparison(a, b)}`;
}
function assessBabyName(candidate, parentEntries) {
  const p = profile(candidate);
  const opposing = new Set(['نار/ماء','ماء/نار','هواء/تراب','تراب/هواء']); const friends = new Set(['نار/هواء','هواء/نار','ماء/تراب','تراب/ماء']);
  if (!p.leaders.length) return { compatible: false, score: 0, p, relations: [], reason: 'الاسم لا يحتوي على حروف عربية محسوبة.' };
  if (p.leaders.some(x => p.leaders.some(y => x !== y && opposing.has(`${x}/${y}`)))) return { compatible: false, score: 0, p, relations: [], reason: 'طبائع الاسم نفسه متضادة حسابيًا.' };
  let score = 0; const relations = [];
  for (const entry of parentEntries) {
    const parent = entry.profile;
    if (p.leaders.some(x => parent.leaders.some(y => opposing.has(`${x}/${y}`)))) return { compatible: false, score: 0, p, relations, reason: `يوجد تضاد حسابي مع ${entry.label}.` };
    const relation = p.leaders.some(x => parent.leaders.includes(x)) ? 'انسجام' : p.leaders.some(x => parent.leaders.some(y => friends.has(`${x}/${y}`))) ? 'صداقة' : 'امتزاج';
    score += relation === 'انسجام' ? 3 : relation === 'صداقة' ? 2 : 1; relations.push({ label: entry.label, relation });
  }
  return { compatible: true, score, p, relations, reason: 'لا يوجد تضاد حسابي مع بيانات الوالدين المدخلة.' };
}
function babyVerdict(match, parentCount) {
  if (!match?.compatible) return 'غير متوافق حسابيًا';
  const ratio = match.score / Math.max(1, parentCount * 3);
  return ratio >= 1 ? 'متوافق جدًا' : ratio >= .67 ? 'متوافق' : 'متوافق بدرجة مقبولة';
}
function suggestedNameList(items, emptyText) {
  if (!items.length) return `<p class="muted empty-state">${emptyText}</p>`;
  return `<div class="name-options">${items.slice(0, state.suggestionLimit).map(x => `<button class="name-option" data-select-name="${esc(x.name)}"><span><strong>${esc(x.name)}</strong><small>${x.p.leaders.join(' / ')} · ${x.relations.map(r => r.relation).join(' + ')}</small></span><em>${babyVerdict(x, x.relations.length)}</em></button>`).join('')}</div>`;
}
function suggestions() {
  const father = profile(state.father), mother = profile(state.mother);
  const parentEntries = [{ label: 'الأب', name: state.father, profile: father }, { label: 'الأم', name: state.mother, profile: mother }].filter(entry => entry.profile.count);
  const desired = profile(state.desiredBabyName);
  const desiredMatch = desired.count && parentEntries.length ? assessBabyName(state.desiredBabyName, parentEntries) : null;
  const list = (names, query) => names
    .filter(name => name !== state.father && name !== state.mother)
    .filter(name => !query.trim() || name.includes(query.trim()))
    .map(name => ({ name, ...assessBabyName(name, parentEntries) }))
    .filter(item => item.compatible)
    .sort((a,b) => b.score-a.score || a.p.count-b.p.count || a.name.localeCompare(b.name, 'ar'));
  const males = parentEntries.length ? list(maleNames, state.maleSearch) : [];
  const females = parentEntries.length ? list(femaleNames, state.femaleSearch) : [];
  const desiredResult = !desired.count
    ? '<div class="baby-empty"><b>اكتب الاسم المرغوب</b><span>سنحسب قيمته ونقارنه بالأب والأم فورًا.</span></div>'
    : !parentEntries.length
      ? `<div class="baby-result neutral"><div><span class="muted">حساب الاسم</span><strong>${num(desired.total)}</strong></div><p>أدخل اسم الأب أو الأم لإظهار درجة التوافق.</p></div>`
      : `<div class="baby-result ${desiredMatch.compatible ? 'compatible' : 'incompatible'}"><div class="baby-result-head"><div><span class="muted">نتيجة ${esc(state.desiredBabyName)}</span><strong>${num(desired.total)}</strong></div><span class="status-badge">${babyVerdict(desiredMatch, parentEntries.length)}</span></div><div class="baby-facts"><span>الطبع <b>${desired.leaders.join(' / ') || '—'}</b></span><span>الكوكب <b>${desired.planetLeaders.join(' / ') || '—'}</b></span><span>البرج <b>${desired.zodiac ? desired.zodiac[0] : '—'}</b></span></div>${desiredMatch.relations.length ? `<div class="relation-chips">${desiredMatch.relations.map(item => `<span>${item.label}: <b>${item.relation}</b></span>`).join('')}</div>` : ''}<p>${desiredMatch.reason}</p></div>`;
  return `<section class="card baby-planner"><div class="section-heading"><div><h2>اقتراح اسم مولود</h2><p class="muted">أدخل بيانات الوالدين ثم جرّب اسمًا مرغوبًا أو اختر من المقترحات.</p></div><span class="tag">NAME-SUGGEST-2.0</span></div><p class="notice">اقتراح حسابي تراثي اختياري؛ المعنى الحسن وسنّة التسمية مقدمان، وليس حكمًا شرعيًا.</p><div class="baby-inputs"><label><span>اسم الأب</span><input data-field="father" value="${esc(state.father)}" placeholder="مثال: محمد"></label><label><span>اسم الأم</span><input data-field="mother" value="${esc(state.mother)}" placeholder="مثال: فاطمة"></label><label class="desired-name"><span>الاسم المرغوب للمولود</span><input data-field="desiredBabyName" value="${esc(state.desiredBabyName)}" placeholder="اكتب الاسم الذي تفكران فيه"></label></div>${desiredResult}<div class="actions"><button class="btn" data-parent-example>تجربة محمد × فاطمة</button><button class="btn" data-clear="parents">مسح بيانات المولود</button></div></section>${parentEntries.length ? `<div class="suggestion-columns"><section class="card suggestion-panel"><div class="suggestion-title"><div><span class="gender-mark male">ذ</span><div><h3>أسماء ذكور مقترحة</h3><span class="muted">${num(males.length)} اسمًا متوافقًا</span></div></div></div><input data-field="maleSearch" value="${esc(state.maleSearch)}" placeholder="ابحث في أسماء الذكور…">${suggestedNameList(males, 'لا توجد أسماء ذكور مطابقة للبحث.')}</section><section class="card suggestion-panel"><div class="suggestion-title"><div><span class="gender-mark female">أ</span><div><h3>أسماء إناث مقترحة</h3><span class="muted">${num(females.length)} اسمًا متوافقًا</span></div></div></div><input data-field="femaleSearch" value="${esc(state.femaleSearch)}" placeholder="ابحث في أسماء الإناث…">${suggestedNameList(females, 'لا توجد أسماء إناث مطابقة للبحث.')}</section></div>${(males.length>state.suggestionLimit || females.length>state.suggestionLimit) ? '<div class="actions centered"><button class="btn" data-more-names>عرض أسماء أكثر</button></div>' : ''}` : '<section class="card baby-prompt"><b>ابدأ باسم الأب أو الأم</b><span>بعدها ستظهر هنا قوائم منفصلة للأسماء الذكور والإناث.</span></section>'}`;
}
const PLANETARY_WEEK = [
  ['الأحد', 'الشمس', '☉', 'sun'], ['الاثنين', 'القمر', '☾', 'moon'], ['الثلاثاء', 'المريخ', '♂', 'mars'],
  ['الأربعاء', 'عطارد', '☿', 'mercury'], ['الخميس', 'المشتري', '♃', 'jupiter'], ['الجمعة', 'الزهرة', '♀', 'venus'], ['السبت', 'زحل', '♄', 'saturn']
];
const AWFAQ_SOURCES = [
  ['المكتبة الوطنية الأمريكية للطب', 'الأوفاق في المخطوطات الطبية والتعويذية', 'https://www.nlm.nih.gov/hmd/arabic/astrology1.html'],
  ['جامعة Warwick', 'دراسة أكاديمية عن بدايات أدبيات الأوفاق العربية', 'https://wrap.warwick.ac.uk/id/eprint/117867/1/WRAP-new-light-early-arabic-literature-Hallum-2020.pdf'],
  ['Oxford Academic', 'السياق التاريخي للأوفاق والحروف والأعمال المنسوبة إليها', 'https://academic.oup.com/book/61617/chapter/539191501'],
  ['University College London', 'الأسبوع الكوكبي وترتيب أيامه التاريخي', 'https://discovery.ucl.ac.uk/10115451/1/Bultrighini_Chapter%2010_LATEST%20copy%202.pdf'],
  ['مكتبة Bodleian – Oxford', 'وصف مخطوط كتاب البلهان', 'https://digital.bodleian.ox.ac.uk/objects/5c9da286-6a02-406c-b990-0896b8ddbbb0/'],
  ['المركز الوطني للفنون – IGNCA', 'كتالوج أكاديمي للأحجبة العربية والفارسية', 'https://ignca.gov.in/Asi_data/43060.pdf'],
  ['دار الإفتاء المصرية', 'فتوى رسمية بشأن السحر والاستعانة بالجن والأحجبة الباطلة', 'https://www.dar-alifta.org/en/fatwa/details/7811/do-the-ruqyah-verses-of-the-quran-drive-away-magic-and-sorcery']
];
function awfaqSquare() { const source = state.awfaqText || state.text; const result = analyze(source); const magic = makeMagicSquare(state.rank, result.total); const sums = magic.grid.map(row => row.reduce((s,x)=>s+x,0));
  return `<div class="grid"><main><section class="card"><div class="section-heading"><div><h2>الوفق العددي</h2><p class="muted">مربع رياضي منتظم؛ تبقى الصفوف والأعمدة والقطران متساوية.</p></div><span class="tag">MATHEMATICAL</span></div><textarea id="awfaqText" rows="3" placeholder="اكتب النص الذي تريد تعميره به…">${esc(state.awfaqText)}</textarea><div class="actions"><label class="chip">الرتبة <select id="rank" style="width:auto;padding:0;border:0;background:transparent">${[3,4,5,7,8].map(n=>`<option value="${n}" ${state.rank===n?'selected':''}>${n}×${n}</option>`).join('')}</select></label><button class="btn" data-use-calculator>استخدم نص الحاسبة</button></div><div class="result"><div class="reference"><div>المجموع S<br><b>${num(result.total)}</b></div><div>ثابت C<br><b>${num(magic.C)}</b></div><div>a / d<br><b>${num(magic.a)} / ${num(magic.d)}</b></div><div>خط M<br><b>${num(magic.M)}</b></div><div>الفرق δ<br><b>${num(magic.delta)}</b></div></div></div><div class="magic" style="grid-template-columns:repeat(${magic.n},1fr)">${magic.grid.flatMap((row,r)=>row.map((value,c)=>`<span class="${r===c || r+c===magic.n-1?'diag':''}">${num(value)}</span>`)).join('')}</div><div class="notice">التحقق الرياضي: مجموع كل صف ${num(sums[0] || 0)} — وفق تام دائمًا. لا يثبت هذا أي أثر غيبي. <span class="tag">AWFAQ-SESIANO-2.1</span></div></section></main><aside><section class="card awfaq-summary"><span class="summary-icon">▦</span><h3>عنوان الوفق</h3><p>وفق ${magic.n}×${magic.n} · ثابت الخط M = <b>${num(magic.M)}</b></p><div class="actions"><button class="btn primary" data-copy-magic>نسخ الشبكة</button><button class="btn" data-export-awfaq>تصدير صورة</button><button class="btn" data-copy-link>نسخ الرابط</button></div></section><section class="card boundary-mini"><b>حدود النتيجة</b><p>الأرقام هنا ناتجة عن خوارزمية رياضية فقط، وليست طلسماً أو تنبؤًا.</p><button class="text-button" data-awfaq-mode="history">اقرأ الخلفية التاريخية ←</button></section></aside></div>`; }
function awfaqHistory() {
  const today = new Date().getDay();
  const days = PLANETARY_WEEK.map(([day, planet, symbol, tone], index) => `<article class="planet-day ${tone} ${today === index ? 'is-today' : ''}"><div class="planet-symbol">${symbol}</div><div><small>${day}${today === index ? ' · اليوم' : ''}</small><strong>${planet}</strong></div></article>`).join('');
  const sources = AWFAQ_SOURCES.map(([institution, title, url], index) => `<a class="source-link" href="${url}" target="_blank" rel="noreferrer"><span>${num(index + 1)}</span><div><strong>${institution}</strong><small>${title}</small></div><b aria-hidden="true">↗</b></a>`).join('');
  return `<section class="heritage-hero"><div><span class="eyebrow">قراءة تاريخية موثقة</span><h2>الأوفاق بين الرياضيات والمخطوطات</h2><p>تفصل هذه الصفحة بين ما وثقته المصادر تاريخيًا، وما لا يمكن تقديمه كحقيقة علمية أو دينية.</p></div><div class="heritage-seal"><span>٧</span><small>مراسلات<br>تاريخية</small></div></section>
  <section class="boundary-grid"><article class="boundary-card confirmed"><span>✓</span><div><small>موثّق تاريخيًا</small><h3>مربعات عددية واستعمالات تعويذية</h3><p>ظهرت الأوفاق كمربعات رياضية، ثم دخلت بعض المخطوطات في سياقات للحماية والتداوي وأغراض أخرى.</p></div></article><article class="boundary-card unproven"><span>≈</span><div><small>غير مثبت علميًا</small><h3>لا دليل على التأثير الغيبي</h3><p>المراسلات الكوكبية والروحانية موروثات تاريخية؛ لا يثبتها انتظام الأرقام ولا يقدمها التطبيق كتنبؤ.</p></div></article><article class="boundary-card religious"><span>!</span><div><small>تنبيه ديني</small><h3>لا استحضار ولا استعانة بالجن</h3><p>يعرض التطبيق المعلومة للدراسة فقط، ولا يقدم أحجبة أو طقوسًا أو تعليمات روحانية.</p></div></article></section>
  <section class="card planetary-section"><div class="section-heading"><div><span class="eyebrow">الأسبوع الكوكبي</span><h2>مراسلات أيام الأسبوع</h2><p class="muted">ترتيب تاريخي موثق في تقاليد فلكية وتنجيمية قديمة، وليس وصفًا علميًا لتأثير الكواكب.</p></div><span class="historical-badge">للعرض التاريخي فقط</span></div><div class="planet-week">${days}</div></section>
  <div class="heritage-notes"><section class="card"><span class="note-number">١</span><h3>هل توجد أوفاق للخير والشر؟</h3><p>تذكر المصادر أعمالًا نُسبت إلى «النور والظلمة» أو إلى النفع والضرر. الفرق كان في <b>الغاية المنسوبة للعمل</b>، لا في القاعدة الرياضية للمربع نفسه.</p></section><section class="card"><span class="note-number">٢</span><h3>ماذا عن الملائكة وملوك الجن؟</h3><p>ربطت بعض المخطوطات الأيام والكواكب بملائكة أو أرواح أو ملوك من الجن، لكن القوائم والأسماء تختلف وليست عقيدة دينية موحدة أو حقيقة قابلة للتحقق.</p></section><section class="card"><span class="note-number">٣</span><h3>كيف يتعامل التطبيق معها؟</h3><p>لا يحسب «ملك اليوم»، ولا ينشئ عملًا للخير أو الضرر. نحافظ على الوفق العددي كأداة رياضية ونضع التراث في متحف معرفي منفصل.</p></section></div>
  <section class="evidence-callout"><div class="evidence-icon">i</div><div><h3>قاعدة العرض داخل التطبيق</h3><p>ورود المعلومة في مخطوط قديم يثبت وجود الفكرة تاريخيًا، لكنه لا يثبت صحتها أو فاعليتها. ووفق فتوى دار الإفتاء المصرية، يحذر التطبيق بوضوح من السحر والاستعانة بالجن والأحجبة الباطلة.</p></div></section>
  <section class="card sources-section"><div class="section-heading"><div><span class="eyebrow">المراجع</span><h2>مصادر مؤسسية وأكاديمية</h2><p class="muted">تفتح الروابط المصدر الأصلي لمراجعة المعلومة وسياقها.</p></div><span class="tag">SOURCES-1.0</span></div><div class="source-list">${sources}</div></section>`;
}
function awfaq() {
  return `<section class="awfaq-switcher" aria-label="أقسام الأوفاق"><button class="${state.awfaqMode === 'square' ? 'active' : ''}" data-awfaq-mode="square"><span>▦</span><div><b>الوفق العددي</b><small>الحاسبة الرياضية</small></div></button><button class="${state.awfaqMode === 'history' ? 'active' : ''}" data-awfaq-mode="history"><span>⌁</span><div><b>الخلفية التاريخية</b><small>المصادر وحدود المعلومة</small></div></button></section>${state.awfaqMode === 'history' ? awfaqHistory() : awfaqSquare()}`;
}
function reference() { return `<section class="card"><h2>المرجع والمنهج</h2><p class="muted">كل النتائج حسابية بمنهج معلن. لا يستخدم التطبيق أبجدًا مغربيًا أو طالعًا فلكيًا أو مضاعفة للشدة.</p><div class="reference"><div class="card"><h3>الأبجد المشرقي</h3>${Object.entries(ABJAD).map(([l,v])=>`<span class="letter">${l} = ${num(v)}</span>`).join(' ')}</div><div class="card"><h3>الطبائع</h3>${Object.entries(ELEMENTS).map(([e,l])=>`<p><b>${e}</b>: ${l.join(' ')}</p>`).join('')}</div><div class="card"><h3>الكواكب</h3>${PLANETS.map((p,i)=>`<p>${i+1}. ${p}</p>`).join('')}</div><div class="card"><h3>البروج</h3>${ZODIAC.map(([z,e],i)=>`<p>${num(i+1)}. ${z} · ${e}</p>`).join('')}</div></div><div class="actions"><button class="btn primary" data-run-tests>تشغيل الاختبارات الذاتية</button><button class="btn" data-reset-storage>مسح البيانات المحفوظة</button></div><span class="tag">GHALIB-SIRR-1.0 · TABIA-MASHRIQI-1.0 · FALAK-STATIC-1.0 · BURJ-MOD12-1.0</span></section>`; }
function render() { const sectionViews = { calculator, names, awfaq, reference }; const result = analyze(state.text); app.innerHTML = `<div class="shell"><header class="top"><div class="brand"><h1>حساب الجمل</h1><small>إبراهيم بن صلاح · أداة حساب تراثية موثقة</small></div><button class="sum-chip" data-go-calculator><span>المجموع الحالي</span>${num(result.total)}</button></header><nav class="nav">${[['calculator','الحاسبة'],['names','الأسماء'],['awfaq','الأوفاق'],['reference','المرجع']].map(([id,label])=>`<button class="${state.section===id?'active':''}" data-nav="${id}">${label}</button>`).join('')}</nav>${sectionViews[state.section]()}</div>`; attach(); }
function parseArabicNumber(raw) { return Number(String(raw).replace(/[٠-٩]/g, d => '٠١٢٣٤٥٦٧٨٩'.indexOf(d)).replace(/[^0-9]/g,'')) || 0; }
function commitText(value) { state.text = value; persist(); }
function recordHistory() { const value = state.text.trim(); const result = analyze(value); if (value && result.total) state.history = [{ text:value, total:result.total }, ...state.history.filter(x => x.text !== value)].slice(0, 5); }
let redrawTimer;
function redrawKeepingFocus(selector, cursor) {
  clearTimeout(redrawTimer);
  redrawTimer = setTimeout(() => {
    if (selector === '#text') recordHistory();
    render();
    const field = document.querySelector(selector);
    if (field) { field.focus(); field.setSelectionRange?.(cursor, cursor); }
  }, 260);
}
function attach() { document.querySelectorAll('[data-nav]').forEach(e=>e.onclick=()=>setSection(e.dataset.nav)); document.querySelector('[data-go-calculator]')?.addEventListener('click',()=>setSection('calculator'));
  document.querySelectorAll('[data-awfaq-mode]').forEach(e=>e.addEventListener('click',()=>{state.awfaqMode=e.dataset.awfaqMode;persist();render();}));
  document.querySelector('#text')?.addEventListener('input', e=>{ const cursor=e.target.selectionStart; commitText(e.target.value); redrawKeepingFocus('#text', cursor); }); document.querySelector('#target')?.addEventListener('input', e=>{const cursor=e.target.selectionStart;state.target=e.target.value;persist();redrawKeepingFocus('#target',cursor);}); document.querySelectorAll('[data-example]').forEach(e=>e.onclick=()=>{commitText(e.dataset.example);render();}); document.querySelectorAll('[data-history]').forEach(e=>e.onclick=()=>{state.text=state.history[e.dataset.history].text;persist();render();});
  document.querySelectorAll('[data-field]').forEach(field=>{const update=event=>{const input=event.currentTarget;const cursor=typeof input.selectionStart==='number'?input.selectionStart:null;const selector=`[data-field="${input.dataset.field}"]`;state[input.dataset.field]=input.value;persist();if(input.tagName==='SELECT')render();else redrawKeepingFocus(selector,cursor);};field.addEventListener('input',update);field.addEventListener('change',update);}); document.querySelector('#awfaqText')?.addEventListener('input',e=>{const cursor=e.target.selectionStart;state.awfaqText=e.target.value;persist();redrawKeepingFocus('#awfaqText',cursor);}); document.querySelector('#rank')?.addEventListener('change',e=>{state.rank=Number(e.target.value);persist();render();});
  document.querySelectorAll('[data-send]').forEach(e=>e.onclick=()=>{ if(e.dataset.send==='names') state.nameA=state.text; else state.awfaqText=state.text; setSection(e.dataset.send); }); document.querySelector('[data-name-example]')?.addEventListener('click',()=>{state.nameA='داود';state.nameB='جالوت';persist();render();}); document.querySelector('[data-parent-example]')?.addEventListener('click',()=>{state.father='محمد';state.mother='فاطمة';state.desiredBabyName='';state.maleSearch='';state.femaleSearch='';state.suggestionLimit=12;persist();render();}); document.querySelectorAll('[data-select-name]').forEach(e=>e.addEventListener('click',()=>{state.desiredBabyName=e.dataset.selectName;persist();render();document.querySelector('[data-field="desiredBabyName"]')?.scrollIntoView({behavior:'smooth',block:'center'});})); document.querySelector('[data-use-calculator]')?.addEventListener('click',()=>{state.awfaqText=state.text;persist();render();}); document.querySelector('[data-more-names]')?.addEventListener('click',()=>{state.suggestionLimit+=12;persist();render();});
  document.querySelector('[data-copy-result]')?.addEventListener('click',()=>{const r=analyze(state.text);copy(`${state.text}\nالمجموع: ${num(r.total)}\nعدد الحروف: ${num(r.count)}`)}); document.querySelector('[data-copy-comparison]')?.addEventListener('click',copyNameComparison); document.querySelector('[data-copy-magic]')?.addEventListener('click',()=>{const m=makeMagicSquare(state.rank,analyze(state.awfaqText||state.text).total);copy(m.grid.map(row=>row.map(num).join(' | ')).join('\n'));}); document.querySelectorAll('[data-copy-name]').forEach(e=>e.onclick=()=>copy(e.dataset.copyName)); document.querySelectorAll('[data-copy-link]').forEach(e=>e.onclick=copyShareLink);
  document.querySelector('[data-export-calculator]')?.addEventListener('click',()=>{const r=analyze(state.text);if(!r.total)return toast('اكتب نصًا أولًا');exportCard('بطاقة حساب الجمل',[state.text,`المجموع: ${num(r.total)}`,`الحروف المحتسبة: ${num(r.count)}`,`عيّنة الحروف: ${r.letters.slice(0,24).map(x=>x.normalized).join(' ')}`],'hisab-jomal');}); document.querySelector('[data-export-names]')?.addEventListener('click',()=>{const a=profile(`${state.nameA} ${state.motherA}`),b=profile(`${state.nameB} ${state.motherB}`);if(!a.total&&!b.total)return toast('أدخل اسمًا أولًا');exportCard('بطاقة الأسماء',[`${state.nameA || '—'}: ${num(a.total)} · ${a.leaders.join(' / ') || '—'}`,`${state.nameB || '—'}: ${num(b.total)} · ${b.leaders.join(' / ') || '—'}`],'hisab-names');}); document.querySelector('[data-export-awfaq]')?.addEventListener('click',()=>{const r=analyze(state.awfaqText||state.text);if(!r.total)return toast('اكتب نصًا أولًا');const m=makeMagicSquare(state.rank,r.total);exportCard(`وفق ${m.n}×${m.n}`,[`المجموع S: ${num(r.total)}`,`ثابت الخط M: ${num(m.M)}`,`a = ${num(m.a)} · d = ${num(m.d)}`,...m.grid.map(row=>row.map(num).join('  |  '))],'wafq');});
  document.querySelectorAll('[data-clear]').forEach(e=>e.onclick=()=>{if(e.dataset.clear==='calculator'){state.text='';state.target='';}if(e.dataset.clear==='names'){state.nameA='';state.nameB='';state.motherA='';state.motherB='';}if(e.dataset.clear==='parents'){state.father='';state.mother='';state.desiredBabyName='';state.maleSearch='';state.femaleSearch='';state.suggestionLimit=12;}persist();render();toast('تم المسح');}); document.querySelector('[data-run-tests]')?.addEventListener('click',()=>{const tests=[['بسم الله الرحمن الرحيم',786],['داود',15],['جالوت',440],['محمد',92],['فاطمة',135],['أإآء',4]];const passed=tests.every(([x,n])=>analyze(x).total===n);toast(passed?'نجحت جميع الاختبارات المرجعية':'فشل اختبار ذاتي');}); document.querySelector('[data-reset-storage]')?.addEventListener('click',()=>{localStorage.removeItem('hisab-jomal-state');location.reload();}); }
render();
